### ISSUE TITLE
Unbinding does not reset state

### ISSUE THREAD

**Issue by jamesAtcodeninja** [posva/vuexfire#127]
Unbinding on a store module successfully stops the listener but it does not reset the state to its original state i.e. `null` or `[]`

**Comment by posva** [comment]
that is intentional, you have to do it manually. This is because that way while rebinding between different refs, there's always something in the state

**Comment by chrisbraddock** [comment]
@posva since I ran in to this issue as well, perhaps it's something you'd consider putting this functionality behind an optional flag in a future release.

It seems a common use case, e.g. when navigating between pages, I'm unbinding references and not binding to anything else at all.

It's not a huge deal to do it manually but it'd be great to have the convenience of VuexFire doing that bit of work.

**Comment by posva** [comment]
I thought a bit more about it and, to not break compatibility, I can add it behind a flag. But I actually think it (resetting to null or []) should be the default when manually unbinding because if you're binding to something else, it's better to use bind directly (which unbinds for you without resetting the data)

At first I didn't want to add it because it's the same behaviour on vuefire, but it may change for firestore

**Comment by bsaf** [comment]
A follow-up question on this – if you try binding to a document that turns out not to exist, the previously bound reference is not unset. Is this intentional?

**Example**

- You're binding using a $route param: /item/123
- User types a $route param that doesn't exist: /item/xxx

If you're reusing the same component then the URL changes, the bindRef fires, but there is no /item/xxx so the data stays bound to /item/123.

Not sure what the ideal is here, just wondering what you think @posva 🤔

**Comment by posva** [comment]
Yes, that's intentional but it may change in the future when unbinding directly, or behind an option. For the moment you have to reset it yourself

**Comment by bsaf** [comment]
Makes sense, thanks! 👍🏼

**Comment by posva** [comment]
Moving this to vuefire repo before archiving vuexfire repo
