### ISSUE TITLE
Manually controlling population of references

### ISSUE THREAD

**Issue by fightwithcrayon** [posva/vuexfire#147]
When working with a large data set, the population of reference fields with data from the referenced child can take quite a long time – and increase the size of data in memory significantly.

While one option would be to exclude the referenced fields from the query being bound, it would be useful to have the raw reference "address" available in the field, to allow manual population of any required data based on user input.

Is there an option at present to disable this process, is it possible/already something you're looking at, or is it something that's of niche interest so might need to be done via a PR?

**Comment by posva** [comment]
Ha, turns out I didn't pass on the `options` as the second argument to `bind` https://github.com/posva/vuexfire/blob/firestore/src/index.js#L347-L348

There's an option to control that named `maxRefDept` that defaults to 2. You can change it to 0 (once the options object is passed 😆 ) and you will get the text instead. I'm not convinced about having the raw reference object because it isn't serialisable making it harder to debug for novice users. I still need to refactor the common code between vuefire and vuexfire regarding that last aspect, but if you want to submit a fix for the first thing, go ahead 😉

**Comment by fightwithcrayon** [comment]
So there is! Cheers for explaining

I must confess my knowledge of how Firestore works is still really basic at present (as in, only just started poking around), so I thought that the "raw reference object" was in fact the text string. However I'll submit a fix for the other issue shortly.
