### ISSUE TITLE
[vuex] unknown mutation type: users/VUEXFIRE/objectValue

### ISSUE THREAD

**Issue by 19r3ka** [posva/vuexfire#43]
I have been banging my head against the wall trying to solve this yet-another issue I have developping with VuexFire. And the lack of documentation is not helping.

here is my main.js
```
export default new Vue({
  el: '#app',

  // As soon as possible initialize Firebase bindings with Auth and database
  beforeCreate () {
    auth()
      .onAuthStateChanged(user => {
        if (user) {
          // bind the app's currentUser to the firebase user of the same uid
          this.$bindAsObject('users.currentUser', database().ref(`users/${user.uid}`))

          // // bind the app's claims instance to firebase's claims/${uid}
          // this.$bindAsArray('claims', database().ref(`claims/${user.uid}`))
        } else {
          auth()
            .signInAnonymously()
            .catch(this.$handleError)
        }
      }).bind(this)
  },

  render: h => h(App),

  store // inject vuex into all components as this.$store
})
```

and below is the Vuex module definition for 'users'
```
const state = {
  currentUser: null
}

const getters = {
  currentUser: ({ currentUser }) => currentUser,
  isLoggedIn: ({ currentUser }) => !!currentUser
}

const mutations = moduleMutations('users')

export default {
  getters,
  namespaced: true,
  mutations,
  state
}
```

What I get when I run this code is **[vuex] unknown mutation type: users/VUEXFIRE/objectValue** and it seems the bad code section is *this.$bindAsObject('users.currentUser', database().ref(`users/${user.uid}`))*

I just want my local state 'currentUser' to be synced with the registered user of the same uid in the Firebase Realtime Database. Any help or redirection to some documentation would be welcome. Thank you.

**Comment by posva** [comment]
> I have been banging my head against the wall trying to solve this yet-another issue I have developping with VuexFire. And the lack of documentation is not helping

That's definitely not a respectful way to start a question on a repository, especially because the doc (as simple as it may be) is in the README.

It's probably because of the namespace option. If you turn it off, it should work. Also adding the mutations as if it was the rootStore should work. Let me check so I can update the Readme because that's something I don't have

**Comment by 19r3ka** [comment]
My deepest apologies if that came out rude. I quickly wrote that out of
despair after a day going back and forth through Vuefire, Vuexfire, and
Vuex documentation.

With a clearer head, I agree that it came out wrong for someone asking for
help on a library he's using for free. So again, Sorry! 🙊

I'll try removing the namespace and report back ASAP. Thanks.

**Comment by posva** [comment]
@19r3ka Ok, so I checked and the you should add the mutations as if it was in the rootStore: `Vuexfire.mutations` without passing a getter. I'll include that on the Readme, I never thought of it, so thanks a lot for pointing it out.

Don't worry about it, I could feel the despair in those words 😅. I prefer thinking that you used Vuexfire because you thought some value on it but reading that feels like you got forced to use it and that you don't enjoy it. I know how that feels because it has happened to me too and I don't want Vuexfire to be that kind of lib, especially being so tiny

**Comment by 19r3ka** [comment]
Hi @posva : I saw the addition to the README. Extremely helpful. I tested that and it worked like a charm. Thanks for quickly helping me out with this issue.

> I prefer thinking that you used Vuexfire because you thought some value on it but reading that feels like you got forced to use it and that you don't enjoy it.

I do enjoy Vuexfire and prefered it to Vuefire for instance. It is just the whole integration between Vuejs and Firebase that is not as straightforward to me. I have been using VueJS for 3 weeks now coming from the MEAN stack, and it is the first time I am depending on a serverless architecture.

Thanks again.
