### ISSUE TITLE
Bind to nested property in state

### ISSUE THREAD

**Issue by jamesAtcodeninja** [posva/vuexfire#95]
I have declared a property on the state such that it's 
```
export const state = function () {
  return {
    firebase: {
      teams: []
    }
}
```
but when I try to bind I get the error 
```
 VuexFire: cannot bind undefined property 'firebase.teams'. Define it on the state first.
```

To note, however, initializing the state with `'firebase.teams': []` seems to work, but then I am unable to access the data using `this.$store.state.firebase.teams` and can only access it using `this.$store.state['firebase.teams']`.

**Comment by posva** [comment]
Yes, this is intended because being able to write nested properties in the state would complexify and increase (in size) the code base. You can, however, bind properties in vuex modules which are nested.
You can name the property `firebaseTeams` as well, but I'd recommend you to name it just `teams` 🙂
